### ISSUE TITLE
App does not show completed puzzles as being completed

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#41] opened 2022-02-25 23:10 UTC
The website (correctly) shows I completed a particular puzzle (The First Eterna3D puzzle) but the mobile app does not. In fact, the mobile app does not seem to acknowledge any of the non-tutorial puzzles that I have completed on the website, either with a checkmark on the thumbnail or through the filter option on the puzzles. Tested on 1.4.1 on iPhone 8.
![pic1](https://user-images.githubusercontent.com/35237235/155815115-97e8bf7e-b152-4ce0-b854-d8bc4619bfb8.PNG)
![pic2](https://user-images.githubusercontent.com/35237235/155815117-ae5f3057-a810-4107-b17a-18fb654b6b44.png)

**Comment by luxaritas** [comment] 2022-02-25 23:20
Duplicate of #32

**Closed** 2022-02-25 23:20 UTC
Labels: bug
