### ISSUE TITLE
"Load More Labs" button does not reset color

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/eterna-mobile#40] opened 2022-02-25 23:06 UTC
When loading lots of labs and using the button multiple times, the visuals for the "Load More Labs" button stays on/selected-looking every time after the first, even after the extra labs have been loaded. I'd expect it to revert back to the original color. Tested on 1.4.1 on iPhone 8.
![pic1](https://user-images.githubusercontent.com/35237235/155814706-10437a0c-fbe8-40b9-bca3-cade47a2bb91.PNG)
![pic2](https://user-images.githubusercontent.com/35237235/155814710-6bbf2864-60c9-4a0f-949b-ca14ff5d7ef4.png)
![pic3](https://user-images.githubusercontent.com/35237235/155814715-7f0fd018-4d16-479b-886a-1e8f6950d84f.png)

**Comment by luxaritas** [comment] 2022-02-25 23:22
Duplicate of #29

**Closed by luxaritas** 2022-02-25 23:22 UTC
Labels: bug
